default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password # docker-compose.ymlのMYSQL_ROOT_PASSWORD
  host: <%= ENV['DB_HOST'] %> # docker-compose.ymlのservice名
  port: 3306

development:
  <<: *default
  database: report_app_development

test:
  <<: *default
  database: report_app_test

production:
  <<: *default
  database: report_app_production
