default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: 'root'
  password: 'password'
  host: 'db'
  port: 3306

development:
  <<: *default
  database: report_app_development

test:
  <<: *default
  database: report_app_test

production:
  <<: *default
  database: report_app_production
