default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: "127.0.0.1"
  port: 3306

development:
  <<: *default
  database: report_app_development

test:
  <<: *default
  database: report_app_test

production:
  <<: *default
  database: report_app_production
